Created main.yml to set up Github Actions
Code-the-Dream-School/dd-prac-team4-back pull request #20
Opened 2023-08-11 17:36 UTC by NatachaKey

goal: each PR should have formatting, linting, and testing applied

2023-08-13 20:00 UTC, akosasante requested changes

2023-08-13 20:00 UTC, akosasante commented on .github/workflows/main.yml
> +    - uses: actions/checkout@v2
Let's use v3 actually, since that seems to be the latest one: https://github.com/actions/checkout

2023-08-13 20:00 UTC, akosasante commented on .github/workflows/main.yml
> +           run: npm run jest
Indentation; each of the steps should be under the same indentation level:

```suggestion
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run prettier for formatting
      run: npm run format
    - name: Running ESLint for linting
      run: npm run lint:fix
    - name: Run jest for testing
      run: npm run jest
```

2023-08-14 07:25 UTC, NatachaKey commented
@akosasante updated the file, but it still gives 'failure' in Actions tab

2023-08-14 23:02 UTC, akosasante commented
oh YAML is really finicky about indentation; take a look at the first two lines. There's a single space in front of `name` and in front of `on` that need to be removed. 

You can install this extension in VS Code to help catch those formatting issues: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

2023-08-15 07:27 UTC, NatachaKey commented
@akosasante Thank you Akos! I installed this extention but it doesn't let me format the doc (will add images of installed YAMl extention, code with spaces and when I select all the text and press 'Format document' or shift+alt+f nothing happens- I also tried to close vs code and then open it)- not sure why- so I used https://jsonformatter.org/yaml-formatter 
![image](https://github.com/Code-the-Dream-School/dd-prac-team4-back/assets/103755090/391fa0a8-5400-4531-817d-14a01a167aff)
![image](https://github.com/Code-the-Dream-School/dd-prac-team4-back/assets/103755090/8685c464-3297-44e4-9554-4df7d02e4d1d)

2023-08-15 07:39 UTC, NatachaKey commented
@akosasante it failed because of this 
![image](https://github.com/Code-the-Dream-School/dd-prac-team4-back/assets/103755090/5cdaae21-a35a-4c1e-a9a4-ac76e0129a3a)
so I asked @mvstoyan to add  "test": "echo \"Error: no test specified\" && exit 1",
    "jest": "jest" scripts to package json- she is working on jest //not sure if it's a correct solution

2023-08-15 19:46 UTC, akosasante approved these changes
Formatting looks good now :+1:

2023-08-15 19:47 UTC, akosasante commented
For now, feel free to merge @NatachaKey , I'll take a look at the test stuff in @mvstoyan 's branch :+1:

2023-08-16 12:39 UTC, akosasante requested changes
Marina's testing PR has been merged to main. So you should be able to set the command to `npm run test` and succesfully run tests now if you merge main into your branch

2023-08-16 12:39 UTC, akosasante commented on .github/workflows/main.yml
> +        run: npm run jest
```suggestion
        run: npm run test
```

2023-08-16 14:43 UTC, NatachaKey commented
@akosasante Akos, are you referring to just to run jest tests or run github actions? I thought you are talking about github actions- maybe I am wrong.  the thing is that I've created branch **_githubActions_** in GitHub - how can I syncronise GitHub branches I have in GitHub with my local repo- I've tried to fetch all branches  fron gitHub with **git fetch --all**
 but it didn't bring **githubActions** branch to my local repo... I just wanted to run GitHub actions and see how is it

2023-08-16 17:20 UTC, akosasante commented
@NatachaKey I don't think there's an simple way to run Github Actions _locally_ since they're meant specifically for continuous integraiton. However, in this case our action is just running three commands (check formatting, check linting, run tests). So we can just run each of those commands locally ourselves.

I'm not 100% sure why you're getting those timeouts. I would try the following:
- `git fetch --all`
- `git merge origin main` to merge in the latest changes
- `npm install` to make sure you have all required packages installed in your local node_modules
- then try each of the commands

Let me know how it goes

2023-08-17 00:58 UTC, NatachaKey commented
@akosasante I just did  git fetch --all as you recommended- and also was reading about it's difference from git pull. So I understood that git fetch --all only fetches updates, but it doesn't automatically integrate them into a local branch. if we want to merge these changes we should do git merge as you said. I did git merge origin main in   After that I did npm i and run 'npm run test', 'npm run format ' and  'npm run lint:fix' I still get errors in jest 
![image](https://github.com/Code-the-Dream-School/dd-prac-team4-back/assets/103755090/601341d7-7d6a-4199-88fe-068449884c9f)

2023-08-17 02:13 UTC, akosasante commented
@NatachaKey I think because in a recent commit from `main` , the `username` field was added as a `required` field for User. But the tests were written before that. If you add `username: 'ava'` to the User.create call on line 54 of `userController.test.js` then all the tests should pass :white\_check\_mark:

2023-08-17 02:14 UTC, akosasante approved these changes
Fix `username` required field in test and everything should pass and you can merge :white\_check\_mark:

2023-08-17 09:40 UTC, NatachaKey commented
@akosasante thank you so much, Akos, and  sorry I wasn't paying attention to that messages cause we haven't discussed jest with girls yet, but we'll do today

2023-08-17 09:41 UTC, merged